version: 2
jobs:
  build:
    docker:
      - image: andreleoni/app-website-circleci:latest
    working_directory: ~/app
    environment:
      DEPLOYMENT_NAME: app-v1
      PROJECT_ID: microserviceevaluation
      CLUSTER_NAME: microservices
      CLOUDSDK_COMPUTE_ZONE: us-central1-a
      CONTAINER_NAME: app
      IMAGE: andre-leoni
      REG_ID: app
      IMG_TAG: 0.1.0
      PROJECT_NAME: app
      DEPLOYMENT_ENVIRONMENT: production
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install depencencies
          command: |
            bundle install

      - run:
          name: Run specs
          command: |
            rspec

      - run:
          name: Build and Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deployment.sh
            fi
